### ISSUE TITLE
Repo may no longer be needed

### ISSUE THREAD

**Issue by MikeMcQuaid** [AlJohri/dotfiles#1]
As of https://github.com/MikeMcQuaid/strap/pull/79 being merged the `Brewfile` in your dotfiles repository will be automatically linked if you add a `script/setup` to do so so you could migrate your `Brewfile` to there and name it `dotfiles`. Hope that's helpful! Feel free to close this out.

**Comment by AlJohri** [comment]
@MikeMcQuaid awesome! just to clarify, do I need to have both a `Brewfile` and a `script/setup` for this to work properly or can I just have the `Brewfile`?

renaming this repository to try it out

**Comment by MikeMcQuaid** [comment]
@AlJohri You need something to symlink the Brewfile to `~/.Brewfile` and currently that something must be named `script/setup` or `script/bootstrap` 👍
